### ISSUE TITLE
When using an Iphone I only get redirected to facebook or twitter

### ISSUE THREAD

**Issue by hakonamatata** [MurhafSousli/ng2-sharebuttons#103]
Hi

When I try this using an IPhone I only get redirected to the Facebook app or the twitter app. 
There is no sharing happening.

**Comment by MurhafSousli** [comment]
Hi @hakonamatata, this is fixed in version `2.1.2`

**Comment by hakonamatata** [comment]
Great, yeah seems to work in the new version :)
