### ISSUE TITLE
Facebook post image position

### ISSUE THREAD

**Issue by mohitook** [MurhafSousli/ng2-sharebuttons#104]
Hello!

Is it possible to set the image position/size e.g. on Facebook?
Additional question: how is it working, that a few pages(popular ones) has it's own picture - title and description when I'm using only the [url] option? This is interesting because these pages post concept just looks so good and the picture/description position is perfect and I will copy this positioning..

Thanks!

**Comment by MurhafSousli** [comment]
Hi @mohitook,

Unfortunately it is not possbile, you can only set the image URL, however facebook provides some recommendation for the image optimization check this [
Facebook Docs - Image Optimization for Link Page Posts.pdf](https://www.sendspace.com/file/ghqwhr)

To summarize the linked document:

 - Minimum size in pixels is 600x315
 - Recommended size is 1200x630 - Images this size will get a larger display treatment.
 - Aspect ratio should be 1.91:1

Facebook reads the [Open Graph Meta Tags](http://ogp.me/) of a given URL:
```html
<head>
   ...
  <meta property="og:title" content="Example site title">
  <meta property="og:description" content="Example site description">
  <meta property="og:url" content="https://example.com">
  <meta property="og:image" content="https://example.com/cover.png">
</head>
```
So you are expected to have these tags in the head of your website, which will allow facebook (and the others..) to recognize the tags and that what all the popular websites have in their website head.

To understand more try facebook [share debug tool](https://developers.facebook.com/tools/debug/) and test any URL

**Comment by mohitook** [comment]
@MurhafSousli Thanks for the quick answer, and just mention that this modul is really great! Kepp it up!

**Comment by monstrfolk** [comment]
So does the sharebutton support using the image input for facebook..?
This (https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Compatibility) says yes, but I can not get it to work.

**Comment by MurhafSousli** [comment]
@monstrfolk Yes you can, if you can not get it to work, open a new issue with your usage and I will help you

**Comment by monstrfolk** [comment]
https://github.com/MurhafSousli/ngx-sharebuttons/issues/131
