### ISSUE TITLE
Invalid url when not being set

### ISSUE THREAD

**Issue by alex88** [MurhafSousli/ng2-sharebuttons#106]
I'm including share buttons like this:

```
<div class="social-icon facebook" shareButton="facebook" [sbTitle]="'team_share_content' | translate:{name: team.name}">
 <div class="icon"><i class="fa fa-facebook"></i></div>
 <div class="counter" translate>follow_fb_share</div>
</div>
```

however I get in console `[ShareButtons]: Invalid URL, fallback to Window URL`, looking at the variables the url seems to be the window url, but url encoded, like `http%3A%2F%2Flocalhost%3A3000%2Fteams%2F56598%`

**Comment by MurhafSousli** [comment]
@alex88 regardless the warning, are you getting any error? 
If you are just confused about the warning, this is normal when you don't provide value for `[sbUrl]`

**Comment by alex88** [comment]
Nope, no errors and everything works, it's just the warning, I thought since there is a check for url in that function, that it could be possible to have an empty url and default to window url without warnings, but if that's expected, no worries :)
