### ISSUE TITLE
Custom share button only allows 1 class

### ISSUE THREAD

**Issue by stevewarsa** [MurhafSousli/ng2-sharebuttons#11]
Thanks for developing this - it is really helpful.  I found an issue that is not a show-stopper, but I would like to correct:

There does not appear to be a way to pass in more than 1 class into a custom share button. For example here is a custom method I've written:

  getTwitterButton(): ShareButton {
    let twitterButton = new ShareButton(
      ShareProvider.TWITTER,
      "<i class='fa fa-twitter' aria-hidden='true'></i> Tweet",
      'btn btn-primary'
    );
    return twitterButton;
  }

This throws an error:

inline template:17:4 caused by: Failed to execute 'add' on 'DOMTokenList': The token provided ('btn btn-primary') contains HTML space characters, which are not valid in tokens

if I just put 'btn' it works fine.

How do I pass in multiple classes?

**Comment by MurhafSousli** [comment]
Hi @stevewarsa, Thanks for opening the issue, I will fix this and let you know when it's updated

**Comment by MurhafSousli** [comment]
Changes are merged and pushed to npm 1.0.7

**Comment by stevewarsa** [comment]
Thanks, I'll check it out...
