### ISSUE TITLE
using binding to pass a dynamic url

### ISSUE THREAD

**Issue by OdaiTu** [MurhafSousli/ng2-sharebuttons#110]
thank you i have a problem with [url] i want to pass a dynamk url form my ts file !
when i use this i got an error 

[url]="'{{myUrl}}'"

**Comment by tinesoft** [comment]
Hi @OdaiTu 

Try just this instead: 

`[url]="myUrl"`

**Comment by OdaiTu** [comment]
i used it like this but it didnt work

**Comment by MurhafSousli** [comment]
Hi @OdaiTu please show your code and what is the error if you are getting one.
