### ISSUE TITLE
Can't override default style

### ISSUE THREAD

**Issue by mateuswetah** [MurhafSousli/ng2-sharebuttons#114]
Following the Documentation, I tried to override the default style with my own css. Although `[defaultStyle]="false"` does disables it, I can't  apply my custom version. [Here goes a modified plunker](https://plnkr.co/edit/7ekWE12xeSqaySH4djfw) from the one you have on Readme.

Am I doing something wrong? Sorry if it's a dumb question. Thanks for the module anyways :)

**Comment by MurhafSousli** [comment]
Hi @mateuswetah that plunker is outdated, here is an updated [plunker](https://plnkr.co/edit/cpCn6mFpY60Eh4leRYsY?p=preview), make sure to add the custom css in the global style, not from the component stylesheet

**Comment by mateuswetah** [comment]
Oh, ok, that works. :)
