### ISSUE TITLE
Callback functions after the share functionality is done

### ISSUE THREAD

**Issue by cenjennifer** [MurhafSousli/ng2-sharebuttons#12]
Hi - I was wondering if it's possible (and if so, how) I can trigger callback functions after a social media link is triggered and complete. Thanks!

**Comment by MurhafSousli** [comment]
Hi @cenjennifer, it seems possible [here](http://stackoverflow.com/a/3291931/1015648), I will add this as an output when I get the time (probably next week), and it will be used like this
```javascript
<share-buttons (windowClosed)="someCallbackFunction"></share-buttons>
```
It's pretty nice to have, thank you

**Comment by cenjennifer** [comment]
Thank you @MurhafSousli

**Comment by MurhafSousli** [comment]
@cenjennifer It's merged in 1.1.0

```html
<share-buttons (popUpClosed)="someCallbackFun($event)"></share-buttons>
```
```javascript
someCallbackFun(event: ShareProvider){
}
```

**Comment by mdd1704** [comment]
Is this still working in Angular 5?

**Comment by MurhafSousli** [comment]
@mdd1704 Yes but the output has changed to `(closed)`

**Comment by mdd1704** [comment]
@MurhafSousli awesome! Thanks for fast response.

**Comment by MurhafSousli** [comment]
it is now called `(closed)`

**Comment by nebiyuelias1** [comment]
Is there any way to know if the share was successful? If someone closes the share dialog without actually sharing the closed event is fired.

**Comment by MurhafSousli** [comment]
@nebiyuelias1 No, that is not possible. there is no event that can tell if the user has actually shared or not

**Comment by nebiyuelias1** [comment]
Ok, What if I want the share count?

**Comment by sohilmordiya** [comment]
> Ok, What if I want the share count?

Hello @nebiyuelias1 @MurhafSousli 

Did you find the solution to this problem?

**Comment by nebiyuelias1** [comment]
> > Ok, What if I want the share count?
> 
> Hello @nebiyuelias1 @MurhafSousli
> 
> Did you find the solution to this problem?

oh I'm no longer using this package, sorry!

**Comment by sohilmordiya** [comment]
@nebiyuelias1 

which package you are using for linkedln successfull post count?

**Comment by nebiyuelias1** [comment]
> @nebiyuelias1
> 
> which package you are using for linkedln successfull post count?

sorry I haven't used for linkedin.
