### ISSUE TITLE
Support for Angular 2.0.2

### ISSUE THREAD

**Issue by michaelyara** [MurhafSousli/ng2-sharebuttons#13]
Hello,

We are currently using Angular 2.0.2 and would really like to use your social share module, but it looks as if there is a hard dependency on Angular 2.0.0 in your package.json file. Is this intentional, or did you intend to specify ~2.0.0 or ^2.0.0?

Thanks,
Mike

**Comment by MurhafSousli** [comment]
Hi @michaelyara, 
It just gives warning on npm install but it works with the latest version, now I updated and remove the hard dependency, reinstall it

**Comment by michaelyara** [comment]
Hi @MurhafSousli,

Thank you very much for the prompt response. Unfortunately,  I am still encountering peerDependecy issues. Here is the trace I am getting:
```
npm ERR! peerinvalid The package @angular/common@2.0.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/forms@2.0.2 wants @angular/common@2.0.2
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.2 wants @angular/common@2.0.2
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.2 wants @angular/common@2.0.2
npm ERR! peerinvalid Peer @angular/router@3.0.2 wants @angular/common@2.0.2
npm ERR! peerinvalid Peer ng2-bootstrap@1.1.16 wants @angular/common@^2.0.0
npm ERR! peerinvalid Peer ng2-bs3-modal@0.10.4 wants @angular/common@^2.0.0
npm ERR! peerinvalid Peer ng2-sharebuttons@1.1.1 wants @angular/common@^2.2.4
```

My dependencies are as follows:
```
  "dependencies": {
    "@angular/common": "~2.0.2",
    "@angular/compiler": "~2.0.2",
    "@angular/core": "~2.0.2",
    "@angular/forms": "~2.0.2",
    "@angular/http": "~2.0.2",
    "@angular/platform-browser": "~2.0.2",
    "@angular/platform-browser-dynamic": "~2.0.2",
    "@angular/router": "~3.0.2",
    "@angular/upgrade": "~2.0.2",
    "angular-in-memory-web-api": "~0.1.5",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "file-saver": "^1.3.3",
    "moment": "^2.14.1",
    "ng2-bootstrap": "^1.1.16",
    "ng2-bs3-modal": "^0.10.4",
    "ng2-cookies": "^1.0.2",
    "ng2-sharebuttons": "^1.1.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "zone.js": "^0.6.25"
  }
```

I was able to get npm install to run successfully by modifying your peerDependencies like so:
```
    "@angular/common": "^2.0.0",
    "@angular/compiler": "^2.0.0",
    "@angular/core": "^2.0.0",
    "@angular/http": "^2.0.0",
    "@angular/platform-browser": "^2.0.0",
    "@angular/router": "^3.0.0",
```

If the issue is somehow on my end, please forgive my ignorance, as npm package management is still fairly new to me.

**Comment by MurhafSousli** [comment]
@michaelyara `peerDependency` is not a big deal, it just warns you that the particular package uses or depends on different version than the one your are using and there might be breaking changes.
As long as it works then there's nothing to be worry about.
I'm closing this for now, but feel free to continue the discussion :smile:

**Comment by michaelyara** [comment]
The issue is that the peerDependecy messages are taken as actual errors and cause `npm install` to exit with a status code of 1, in turn failing our Jenkins build. This is caused by the fact that I am using npm 2.15.5, which will automatically attempt to install peerDependencies.

From the official NPM docs:
```
NOTE: npm versions 1 and 2 will automatically install peerDependencies if they are not explicitly depended upon higher in the dependency tree. In the next major version of npm (npm@3), this will no longer be the case. You will receive a warning that the peerDependency is not installed instead.
```

We can try to move to npm 3, however this may be a bit of an undertaking for us, as we have several developers and automated build systems.

We can also attempt to maintain the modifications I have made to your package.json file manually, but this can be a bit of a pain. 

I believe that the value you have set on Angular peerDependecies is incorrect. A value of `^2.2.4` essentially evaluates to `>=2.2.4 <3.0.0` (https://docs.npmjs.com/misc/semver), which excludes 2.0.2. I believe you should be setting this to `^2.0.0` which evaluates to `>=2.0.0 <3.0.0`, covering the entire major version.

Once again, I may be misunderstanding the way the versioning works, so please forgive me if I am. ^.^

**Comment by MurhafSousli** [comment]
It says [here](http://stackoverflow.com/a/22345808/1015648) that `^` is more relaxed and it should includes bigger range!

> In the simplest terms, the tilde matches the most recent minor version (the middle number). ~1.2.3 will match all 1.2.x versions but will miss 1.3.0.

>The caret, on the other hand, is more relaxed. It will update you to the most recent major version (the first number). ^1.2.3 will match any 1.x.x release including 1.3.0, but will hold off on 2.0.0.

**Comment by michaelyara** [comment]
prasanthv actually makes a correction  in the comments of that post: 

> This is misleading for ^. It says that ^ will update you to the most recent major version, when in actuality it updates you to the most recent minor version. i.e: - ^1.2.3 := >=1.2.3 <2.0.0 - ^0.2.3 := >=0.2.3 <0.3.0 - ^0.0.3 := >=0.0.3 <0.0.4

The rofrlo backs it up:

> @prasanthv is right: from docs.npmjs.com/misc/semver#caret-ranges-1-2-3-0-2-5-0-0-4: Caret Ranges ^1.2.3 ^0.2.5 ^0.0.4. Allows changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple. In other words, this allows patch and minor updates for versions 1.0.0 and above, patch updates for versions 0.X >=0.1.0, and no updates for versions 0.0.X.
