### ISSUE TITLE
 ShareButtonsModule is not an NgModule

### ISSUE THREAD

**Issue by microSoftware** [MurhafSousli/ng2-sharebuttons#15]
Hello, First thanks for your plugin. It's really awesome. Today, I updated angular, angular-cli and node. But I have few error with this plugin.

> node v7.2.0
> angular 2.2.3
> angular-cli : 1.0.0-beta.22-1
> OS : MacOs 10.11.6 (El Capitan)

**ng build return this error :**
`10% building modules 2/2 modules 0 activeShareButtonsModule is not an NgModule
Error: ShareButtonsModule is not an NgModule
    at AotPlugin.getNgModuleMetadata (/Applications/MAMP/htdocs/foo/node_modules/@ngtools/webpack/src/plugin.js:332:19)
    at /Applications/MAMP/htdocs/foo/node_modules/@ngtools/webpack/src/plugin.js:345:51
    at Array.map (native)
    at AotPlugin.extractLoadChildren (/Applications/MAMP/htdocs/foo/node_modules/@ngtools/webpack/src/plugin.js:343:14)
    at AotPlugin._processNgModule (/Applications/MAMP/htdocs/foo/node_modules/@ngtools/webpack/src/plugin.js:272:38)
    at /Applications/MAMP/htdocs/foo/node_modules/@ngtools/webpack/src/plugin.js:242:39
    at process._tickCallback (internal/process/next_tick.js:103:7)`

**And ng build --prod --aot : and (got stuck at 19%)**
`10% building modules 2/2 modules 0 active(node:9701) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unexpected value 'ShareButtonsModule' imported by the module 'AppModule'
(node:9701) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 19% building modules 78/78 modules 0 active`

I think for the first error (with ng build). It's because of the update of angular 2.2.3
But for the second error, I think It's because of the update from node 6 => node 7

Thanks in advance for you help

**Comment by kodeine** [comment]
i think this package does not support AOT yet

**Comment by MurhafSousli** [comment]
Hi @microSoftware, it seems that you are using AOT which is not supported at the moment https://github.com/MurhafSousli/ng2-sharebuttons/issues/14

**Comment by microSoftware** [comment]
Ok, but just the "ng build"  doesn't work neither. It was working on angular 2.1.  And i've updated to angular 2.2 and now It doesn't work anymore. (see my first message to see the error

**Comment by MurhafSousli** [comment]
@microSoftware there should be no problem with `ng build`, I see 

> ng build return this error :
10% building modules 2/2 modules 0 activeShareButtonsModule is not an NgModule Error: ShareButtonsModule is not an NgModule at AotPlugin.getNgModuleMetadata 

it seems that you are using AotPlugin in `ng build` which is AOT right!

**Comment by microSoftware** [comment]
Ah yeah effectively it sounds that it's aot. Which is weird because I just call "ng build" and not "ng build --aot"
Anyway thanks, it's probably an angular-cli issue.
