### ISSUE TITLE
Share button with hashlocationstrategy URL.

### ISSUE THREAD

**Issue by PardeepJain** [MurhafSousli/ng2-sharebuttons#16]
When i am setting Dyanmic Url to share button let suppose

`https://mywebsite.com/#/abc/234`

than your share button will share url only as `https://mywebsite.com` instead of sharing Full URL address.

PS: Binding is dynamic from Rest API.

**Comment by MurhafSousli** [comment]
Hi @PardeepJain, can you show your code?
ShareButtons checks the URL if its valid on `ngAfterViewInit`, if not it will use `window.location.href`, when you change the URL dynamically, it will not be checked but it should work with the URL as you changed it.

```javascript
@Input() url: string;
/** setting URL    */

ngAfterViewInit() {
  if (this.url) {
     /** If URL is presented check if it is a valid URL */
     let r = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
     if (!r.test(this.url)) {
         console.warn('ShareButtons: Invalid URL, switching to window.location.href');
         this.url = this.window ? this.window.location.href : typeof global != 'undefined' ? (<any>global).url : '';
        }
  }
  else {
     this.url = this.window ? this.window.location.href : typeof global != 'undefined' ? (<any>global).url : '';
  }
}
```

**Comment by PardeepJain** [comment]
According to you if ill not provide URL attribute than it will automatically share Current URL ? 

as of now i am using like this without `url` like this

`<share-buttons [reddit]="false" [stumbleUpOn]="false"></share-buttons>`

but still not working as expected ,

i am at url `http://localhost:4200/#/XYZ/191` but share url showing only `http://localhost:4200/#/` why so ?

**Comment by MurhafSousli** [comment]
@PardeepJain the issue is with the `hashlocationstrategy`, currently it will work if you disable the hash, but I will look for it once I get free time and let you know when it's fixed, thanks for letting me know.

**Comment by PardeepJain** [comment]
@MurhafSousli is there any time line when will you resolve this bug ? its urgent for me to use this in hashlocationstrategy

**Comment by MurhafSousli** [comment]
@PardeepJain Unfortunately, I'm busy atm, but if you are in a hurry you can try the following solution until I push the update, 
1 - copy the package [**_source files_**](https://github.com/MurhafSousli/ng2-sharebuttons/tree/master/src) to your project directory
2 - import `ShareButtonsModule` locally (not from _node_modules_ dir)
3 - go to [_**share-button.component.ts**_](https://github.com/MurhafSousli/ng2-sharebuttons/blob/master/src/components/share-button/share-button.component.ts) and just replace `window.location.href` with `encodeURIComponent(window.location.href)` like this
```javascript
ngAfterViewInit() {
    if (this.url) {
        let r = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
        if (!r.test(this.url)) {
            console.warn('ShareButtons: Invalid URL, switching to window.location.href');
            this.url = this.window ? 
                encodeURIComponent(this.window.location.href)
                : typeof global != 'undefined' ? (<any>global).url : '';
        }
    }
    else {
        this.url = this.window ? 
            encodeURIComponent(this.window.location.href) : 
            typeof global != 'undefined' ? (<any>global).url : '';
    }
.....
```
Hope this helps

**Comment by kuldeep89** [comment]
> When i am setting Dyanmic Url to share button let suppose
> 
> `https://mywebsite.com/#/abc/234`
> 
> than your share button will share url only as `https://mywebsite.com` instead of sharing Full URL address.
> 
> PS: Binding is dynamic from Rest API.

@MurhafSousli  same issue, I am  using latest pakage 7.1.4 .... I have tried many thing as per documentation from last 1 day...but it is not solved 
getting problem for linked in and facebook - url I am trying to share is - https://xyz.com/#/share/poster/1354  ....when sharing on  linkedin and facebook....it  is not sharing url sharing ...just showing  or sharing https://xyz.com

Please look into this and help me to solve this....please let me know in case of any other information you needed

**Comment by MurhafSousli** [comment]
Please upgrade to the latest version `8.0.0-beta.3`, see the instruction in #432

**Comment by kuldeep89** [comment]
@MurhafSousli  tried with beta version too...still getting same issue..

> @kuldeep89 Please upgrade to the latest version `8.0.0-beta.3`, see the instruction in #432

checked and tried with beta version too...still getting same issue

**Comment by prachip** [comment]
Hi @MurhafSousli,

I am also trying with version 8.0.2 but still my url is not coming fully for Facebook and linkedin. For Twitter n Whatsapp working fine. I am using url as http://xyz.com/share/ADGT67S, for facebook coming as http://xyz.com

**Comment by MurhafSousli** [comment]
@prachip This seem to be a different issue, please use a new issue, fill the template and add a reproduction stackblitz
