### ISSUE TITLE
Showing error when I import "ShareButtonsModule" in application

### ISSUE THREAD

**Issue by binal24** [MurhafSousli/ng2-sharebuttons#17]
Showing below error like,
"ShareButtonsModule is not an NgModule"

Please help me out for this error.

**Comment by MurhafSousli** [comment]
Hi @binal24, Have you upgraded angular-cli  to 1.0.0-beta.24? [Check this](https://github.com/angular/angular-cli/issues/3157)

**Comment by MurhafSousli** [comment]
This package needs to be recompiled, by the time I push the new updates you can use the source typescript in your project

**Comment by binal24** [comment]
Yes I am using angular-cli 1.0.0-beta.24 version.
Its showing Module error, but its working. 
But my concern is, Is there any issue happens by this error after publishing my application?

**Comment by MurhafSousli** [comment]
@binal24 I don't think so, but next release will ship typescript files instead of compiled ones to avoid such issues in the future

**Comment by tinesoft** [comment]
Hi @MurhafSousli,  

Regarding this issue, the recommenced solution is to publish the  `.metadata.json` files along with the  `.d.ts` files (see [@hansl's comment](https://github.com/angular/angular-cli/issues/3426#issuecomment-269673735).

To do so, you must use the @angular/compiler-cli (ngc), which is a drop-in replacement for Typescript compiler (tsc) with some additional Angular magic, like generating those modules metadata and being AOT compliant.

I have a working PR ready to push if you want.

Cheers
