### ISSUE TITLE
LinkedIn Sharing URL

### ISSUE THREAD

**Issue by MurhafSousli** [MurhafSousli/ng2-sharebuttons#2]
LinkedIn Share button shows the following error in the popup windows
`We’re sorry. Something unexpected happened and your request could not be completed. Please close this window and try again.`

I use this share link which I got from [LinkedIn Offical Docs](https://developer.linkedin.com/docs/share-on-linkedin)
```
linkLinkedin = 'http://www.linkedin.com/shareArticle?url=' + url;
```
Even their example at the end of the page gives the same error.
`https://www.linkedin.com/shareArticle?mini=true&url=http://developer.linkedin.com&title=LinkedIn%20Developer%20Network
&summary=My%20favorite%20developer%20program&source=LinkedIn`

**Comment by MurhafSousli** [comment]
It turns out that linkedIn button was just working perfectly, and the issue was only happening on my end. :feelsgood:

**Comment by Sumita-05** [comment]
> It turned out that linkedIn button was working, and the issue was only happening on my end. :feelsgood:

I am getting same error how did you solve it??
