### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by cuongnm265** [MurhafSousli/ng2-sharebuttons#20]
Hi! In the customization, you say: "Each share service has its own button template, pass your custom button template as string in its input, e.g. give facebook a custom template [facebook]="facebookTemplate"."
What exactly "facebookTemplate" is and how to apply style for other class like: sb-buttons after I set default style to false? Thanks

**Comment by MurhafSousli** [comment]
Hi @cuongnm265, it's the name of the variable that holds the element(s) you want to use for facebook button 

```javascript
@Component({
  selector: 'some-component',
  template:`
<share-buttons [facebook]="facebookTemplate"></share-buttons>
  `
})
export class SomeComponent implements OnInit {

  facebookTemplate = "<img src='../assets/img/custom/facebook.svg'>"
}
``` 
for styling, you just need to use the classes in your css as mentioned in the [doc](https://murhafsousli.github.io/ng2-sharebuttons)

```css
.sb-container{
    //ShareButtons Holder
 }
 .sb-title{
    //Share Title
 }
 .sb-count{
    //Total Share Count
 }
 .sb-buttons{
    //Buttons Container
 }
 .sb-btn{
    //Share Button, the container of the button template 
 }
 .sb-btn-count{
    //Button Share Count
 }
```
