### ISSUE TITLE
AOT compile

### ISSUE THREAD

**Issue by doorman02** [MurhafSousli/ng2-sharebuttons#23]
Hi, thanks for this great library.

I am trying to compile to AOT but I get the following error:
Error: Error encountered resolving symbol values statically. Could not resolve ng2-sharebuttons relative to..

Does the libarary support AOT at this time?

Thanks!

**Comment by doorman02** [comment]
Hi @MurhafSousli I now get the compile error
Property 'tCount' is private and only accessible within class 'ShareButtonsComponent'.
Using version 1.1.3

**Comment by u12206050** [comment]
We are having a similar issue but with Angular Universal and ng2-sharebuttons, the only error message we get is `Uncaught Exception invalid token export` If we remove ng2-sharebuttons, then this error disappears. Any ideas?

**Comment by tinesoft** [comment]
Hi guys, 

@doorman02: Sorry,  we indeed miss that in PR #21.
I'll have a look tonight.

@u12206050:  did you try temporary fix mentioned by @doorman02? (removing  `private` modifier from `tCount` and `buttons` in share-buttons.component.js?

Cheers,

**Comment by sdsanders** [comment]
Can confirm that this is fixed in Angular Universal. I was getting the same `Uncaught Exception invalid token export` using version 1.1.5 but updating to version 2.0.0 (currently published as beta on npm) fixed it for me.
