### ISSUE TITLE
Share URL doesn't update when router URL changes

### ISSUE THREAD

**Issue by git-saurabh** [MurhafSousli/ng2-sharebuttons#34]
When application load, and then i share url it take work properly and when i select value in the drop down, a route will change at this time when i share a url it take old url not initial url.

Ex: 
Steps: 1-  Initial url  when application load:  http://localhost:4200/#/tracker/2015   
Step: 2- Share url , it take http://localhost:4200/#/tracker/2015 ( which is correct )
Step:3 - Change year form drop down,  from 2015 to 2007,  now url change to       http://localhost:4200/#/tracker/2007   

Step:4 - When i share, it take initial url that is  http://localhost:4200/#/tracker/2015 , that the issue, it cannot take current url

Note :  iam not using [url] property of plugin

**Comment by git-saurabh** [comment]
Actually router navigate to same component with different parameters

**Comment by git-saurabh** [comment]
in plugin(ShareButtonComponent)  this.url is set in  ngAfterViewInit(Respond after Angular initializes the component's views and child views.) life cycle hook, but when component navigate  on  same component with different parameters, then plugin ShareButtonComponent dont recreate, so at that time when we click on share button it take initial url not current url.

**Comment by MurhafSousli** [comment]
@git-saurabh I got it.. we will fix this in the next release
