### ISSUE TITLE
[networking] create a gitter community for the project

### ISSUE THREAD

**Issue by tinesoft** [MurhafSousli/ng2-sharebuttons#36]
[Gitter ](https://gitter.im) is a chat and networking platform that helps to manage, grow and connect communities through messaging, content and discovery.

This tool can help us discuss better about future developments on the project (via **private one-to-one chat**), along with allowing public users to ask questions, share tips and experience about using `ng2-sharebuttons`, ...

Once you signed it with you github account, you can create a community from the project: [https://gitter.im/home#createcommunity](https://gitter.im/home#createcommunity)

**Comment by MurhafSousli** [comment]
https://gitter.im/ng2-sharebuttons/Lobby done
