### ISSUE TITLE
Can't get basic example to work

### ISSUE THREAD

**Issue by takariendire** [MurhafSousli/ng2-sharebuttons#4]
I get an error trying to implement the basic example, any idea what the issue is? Thx 
![image](https://cloud.githubusercontent.com/assets/2589867/19276037/2b77d152-8f8a-11e6-9fa2-9d5d3b4ce5cd.png)

**Comment by Abszissex** [comment]
looks like u messed up your template, mind sharing it?

**Comment by MurhafSousli** [comment]
Hi @takariendire, I can't tell from this error, show me your code
