### ISSUE TITLE
hash symbol inside description

### ISSUE THREAD

**Issue by doorman02** [MurhafSousli/ng2-sharebuttons#42]
Hi, I am trying to share the hash symbol in the description variable but it doesn't appear in the sharing dialog. Is this even possible? I know there is the tags variable but I want the hash tags to be part of the description because I am sharing a user comment.

Thanks!

**Comment by MurhafSousli** [comment]
It does not seem to be possible in twitter, for instance try this URL in your browser

https://twitter.com/intent/tweet?url=http://asdas.com&text=Helllo#World

**Comment by doorman02** [comment]
ok thanks, for the information!
