### ISSUE TITLE
Detecting when share button is clicked

### ISSUE THREAD

**Issue by doorman02** [MurhafSousli/ng2-sharebuttons#45]
Hi, thanks alot for your help.
Is it possible to detect which share button is clicked? I need this because I would like to change the description depending on which share button is clicked. Forinstance Twitter might have a shorter description than Facebook since there are total character limits, and I might want to include the title information because Twitter doesn´t use the Title field like Facebook.  

Thanks!

**Comment by MurhafSousli** [comment]
Yupp, you get the clicked button

```html
<share-buttons (popUpClosed)="yourFun($event)">
```
```javascript
yourFun(clickedButton: ShareProvider){

}
```

**Comment by doorman02** [comment]
Hi @MurhafSousli thanks for your help. The popUpClosed event is triggered after sharing. I need an event before the popup opens, so I can change the description before it´s displayed in the sharing dialog that is an event when the share icon button is clicked. Is this possible?

Thanks!

**Comment by MurhafSousli** [comment]
@doorman02 Currently this is not possible out of the box, but you can still do it the way I stated above  ☝️

**Comment by doorman02** [comment]
Do you mean I can somehow change the description before the popup opens?
It would be nice if it would be possible out of the box because different sharing services have different text limits and such. Thanks again for this great plugin :)

**Comment by MurhafSousli** [comment]
@doorman02 Now I got it, I think we can fix the tweet's text limit issue, but it's not possible to filter the `description` before window opens from the **ShareButtons** component, and it would be too specific if you made this possible for the inner component **ShareButton**

**Comment by doorman02** [comment]
Thanks @MurhafSousli for your help. To further explain my use case. I have some important information in the title field and then more information in the description field. This fits well for Facebook sharing dialog. But Twitter doesn´t use the title field, in that case I would like to move the important information from the title to the description field. I am sure there will be similar use cases for the other sharing services. That´s why I was wondering if it was possible to modify the title, description fields on the fly depending on the pressed ShareButton before the sharing dialog opens.

**Comment by MurhafSousli** [comment]
@doorman02 Have you checked the advanced usage I told you about? 
You will be able to that if you added the share button individually, don't use `<share-buttons>`, instead use `<share-button [description]="customTweetText">` 
Please read the [guide](https://murhafsousli.github.io/ng2-sharebuttons/) to learn how to initialize a single share button.

If you have got an out of the box solution, please submit your PR and we will review it

**Comment by doorman02** [comment]
I see, ok thanks I will have a better look :)

**Comment by MurhafSousli** [comment]
:) I'm closing this one now, and opening the tweet text limit issue in separate thread
