### ISSUE TITLE
[url] value from component class

### ISSUE THREAD

**Issue by ericel** [MurhafSousli/ng2-sharebuttons#47]
I get invalid url when I try to pass in the [url] from class.

```
export someclass {
 url = `https://someurl.com/${this.item.sid}/${this.item.item}/`
}
```
```
 <share-buttons [shareTitle]="'Total Shares - '"
      [url]= "'url'"
      ></share-buttons>
```

`ShareButtons: Invalid URL, switching to window.location.href`

**Comment by MurhafSousli** [comment]
Hi @ericel, Here is our `validateURL` function, test it with your URL and tell me if there is a problem

```
validateUrl(url: string) {
        /** If URL is specified then validate it, otherwise use window URL */
        if (url) {
            let r = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;

            if (r.test(url)) {
                return url;
            } else {
                console.warn('[ShareButtons]: Invalid URL, fallback to Window URL');
            }
        }
        /** fallback to "Window" URL, or to "Global" in universal */
        return (this.window) ? encodeURIComponent(this.window.location.href) : (<any>global).url || '';
    }
```

**Comment by ericel** [comment]
@MurhafSousli  the url validates.  
But If I get the url value from the component class to the view template 
```
export someclass {
 url = `https://someurl.com/${this.item.sid}/${this.item.item}/`
}
```
<share-button> `[url] = "'url'"`. I get the invalid url. I think it has something to do with passing the url variable from component class to view template.

**Comment by MurhafSousli** [comment]
@ericel   Did you notice what you just did? :rage3: you are passing inline string instead of the variable
change 
`[url]="'url'"`
to 
`[url]='url'`

**Comment by ericel** [comment]
@MurhafSousli  that won't change a thing. It will still not accept a varable from the component class. I doubt why u closed it. But u are the author. Great job with the module though.

**Comment by tinesoft** [comment]
and what about using the **double-quote** to reference your variable, 

`[url]="url"`

?
This is the proper way to pass input values from the view template.

**Comment by MurhafSousli** [comment]
@ericel closing an issue is not the end of the discussion. I close when I confirm it is not an issue, or in other meaning, no action will be taken regarding to it. 
I personally don't have the owner mentality at all. This project just like any other open source project, saves developers hours of work and we spend time making it better and responding to others issues while most of them skimp to support us with a star. but we like to keep it professional and fun here, just give angular docs more attention and you are always welcome to open new issues
