### ISSUE TITLE
Styles are missing

### ISSUE THREAD

**Issue by Abszissex** [MurhafSousli/ng2-sharebuttons#5]
There are no .sass file in the repository, but you are compiling them in gulp.

could it be that they are missing? at least I am missing a lot of styles in my app (see the picture, "fa fa-facebook" don't get any styles..).
There is nothing displayed, just when I hover over the invisible buttons their color change like it should, but I am missing for example the "\F09A" in the facebook sharing button and so on...

do you have any idea why? Did everything like the readme said.
I would be please if a fast solution is possible, because my project have to be finished in a few days... :(

![unbenannt](https://cloud.githubusercontent.com/assets/4190798/19286953/0d0e89b0-9000-11e6-9530-14fa86249776.PNG)

**Comment by MurhafSousli** [comment]
Hi @Abszissex, I have noted that

> The default icons requires [fontawesome](http://fontawesome.io/) to be loaded into your project.

This means that you have to add fontawesome stylesheet in your project if you want the default icons, you can do this simply by adding the following line in your `index.html` head

`<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">`

There are many ways to load font-awesome stylesheet so I left it up to you
