### ISSUE TITLE
Order of share buttons using `share-buttons` component

### ISSUE THREAD

**Issue by altschuler** [MurhafSousli/ng2-sharebuttons#50]
Is it possible to define the order of the buttons in the share buttons component? I'd like to use the container and everything as it is, but I'd like to customize the order of the providers.

If not, I'll be happy to do a PR if a hint for the implementation could be given :)

Thanks for an awesome library!

**Comment by MurhafSousli** [comment]
Hi @altschuler, yes it is possible through css, we are using flexbox, so you can override the style, for example:
```css
.sb-container .facebook {
  order: 3;
}
```
if it didn't effect add `!important` to force overriding.

you are welcome to do PR, I would like to see simpler/better ways to enhance the module, I also have a plan to improve the default style

**Comment by altschuler** [comment]
Thanks a bunch, that'll work!
