### ISSUE TITLE
Add whatsapp share button

### ISSUE THREAD

**Issue by jcao02** [MurhafSousli/ng2-sharebuttons#51]

**Comment by jcao02** [comment]
I'll probably make a PR to add this feature. Should I do it from your `dev` branch? @MurhafSousli

**Comment by MurhafSousli** [comment]
@jcao02 yupp it's fine 👍

**Comment by jcao02** [comment]
@MurhafSousli the branch doesn't seem to be stable right now. I get an error when compiling with `angular-cli`:
```
ERROR in Error encountered resolving symbol values statically. Could not resolve ng2-sharebuttons relative to ...
```

Is it a problem if I use you `master` branch for the PR?

**Comment by MurhafSousli** [comment]
@jcao02 in root dir, do `gulp build` then `gulp link` then `gulp demo`, ofcourse don't forget to `npm install` in demo first

**Comment by MurhafSousli** [comment]
@jcao02 in case it didn't work for you, copy `src` to `demo/src/share` and import from there temporary, but don't include these changes in the PR

**Comment by MurhafSousli** [comment]
@jcao02 It seems that whatsapp button is not working in `2.0.0@beta`, have you tried it?

**Comment by jcao02** [comment]
Yes. I'm using [this](https://www.npmjs.com/package/@jcao02/ng2-sharebuttons) package while you release the last version. The button only works from a smartphone, though (The link opens the native app)

**Comment by MurhafSousli** [comment]
This need to be fixed for the web too
