### ISSUE TITLE
Not working in systemjs

### ISSUE THREAD

**Issue by aravindfz** [MurhafSousli/ng2-sharebuttons#57]
When I tried to integrate in systemjs based app it is not working. How ever your plugin works in angular-cli. Can you please fix it or guide me through the process, I am ready to contribute as well

**Comment by MurhafSousli** [comment]
Hi @aravindfz, I'm not sure how to do that, if you go a fix submit a PR

**Comment by tinesoft** [comment]
Hi @aravindfz ,

`SystemJS` packaging is on radar.  We are currently making some internal changes with our build tools that will allow distribution of `UMD` bundle for SystemJs, while keeping AoT compatibility.

So stay stuned!
