### ISSUE TITLE
Angular2 Universal support

### ISSUE THREAD

**Issue by u12206050** [MurhafSousli/ng2-sharebuttons#6]
Am getting this error when trying to run ng2-buttons with Angular2's Universal (prerender) on the server side:

```
EXCEPTION: window is not defined
ORIGINAL STACKTRACE:
ReferenceError: window is not defined
    at e.ngAfterViewInit (/var/www/drupal/frontend/universal-starter/node_modules/ng2-sharebuttons/dist/components/share-button/share-button.component.js:1:983)
```

It works without prerender. This is a common error it seems in components that try to use window.

**Comment by MurhafSousli** [comment]
@u12206050 Yup, it uses `window.open()` to open the dialog, let me investigate this further for you

**Comment by u12206050** [comment]
The main problem is the use of window.location.href, I believe angular does have a Location object that you can use. Luckily window.open() doesn't get called when rendering on the server so that isn't such a big deal.

For others wanting to fix this, I did the following to fix the window.location.href:

Replaced `window.location.href` with 
`typeof window != 'undefined' ? window.location.href : typeof global != 'undefined' ? global.url : ''`

And then in server.ts where Universal is being called to render do the following:

```
/* Declare both global and the url property for typescript concerns */
interface Global {
  url: string;
}
declare var global: Global;

/* In the function that responds with the rendered html */
let ngApp = (req, res) => {
  let url = req.originalUrl || '/';
  global.url = url;
}
```

**Comment by MurhafSousli** [comment]
@u12206050 I was thinking to inject `Window` as a provider like in this [SO answer](http://stackoverflow.com/a/37176929/1015648) or this [article](http://juristr.com/blog/2016/09/ng2-get-window-ref/) , I let you know as soon as push the update

**Comment by MurhafSousli** [comment]
@u12206050  I got it, it turned out that there's no `window` in node, so we will use `@ViewChild('firstModal')` to get it work

**Comment by u12206050** [comment]
Is this fixed now?

**Comment by MurhafSousli** [comment]
@u12206050  I have played with Universal yet, but now sharebuttons will only use `window.location.href` if the `[url]` input is not provided, so pass your current url to the input and it should work

**Comment by MurhafSousli** [comment]
@u12206050  For opening share window which uses `window.open` I'm not sure how to it this in Universal
![capture](https://cloud.githubusercontent.com/assets/8130692/19741361/081de322-9bc9-11e6-9c41-09e9bb928e93.PNG)
I would have made the share window to open in a modal, but some social sites like fb have `SAMEORIGIN` policy, which means that they have disallowed loading of the resource in an iframe outside of their domain...

btw are you getting errors while compiling or at run time?

**Comment by u12206050** [comment]
Could you just please do the following, it fixes compiling on universal side at least.
Replaced `window.location.href` with 
`typeof window != 'undefined' ? window.location.href : typeof global != 'undefined' ? global.url : ''`

**Comment by MurhafSousli** [comment]
@u12206050 okay it's merged now, please download the source manually and test it in your app, if it works I will push it to npm, because I'm not sure if it would work with `window.open`. isn't it a problem for universal compiling? how would universal open links?

btw: I tried to replace  `window.location.href` with `router.url`, `location.path()` and `location.prepareExternalUrl(location.path())`, they all don't return the full path, also I couldn't find any alternative to `window.open`. we can't get rid of it

**Comment by u12206050** [comment]
Ok, the changes should work, except that window and global are undefined in the context of typescript when compiling. I made a merge request with the interfaces for them.

**Comment by MurhafSousli** [comment]
I tried to use it on a new [Universal Starter](https://github.com/angular/universal-starter) installation, I imported `ShareButtonsModule` in both `app.browser.module` and  `app.node.module`, it worked.
The only issue I found is when I click on Pinterest button. `Cannot read property 'getAttribute' of null`, but everything else is working as expected!
![capture](https://cloud.githubusercontent.com/assets/8130692/20279684/27f45d14-aab2-11e6-9a3e-b380dade3f34.PNG)

**Comment by MurhafSousli** [comment]
Changes are merged and pushed to npm in 1.0.7

**Comment by u12206050** [comment]
Did you make use of the share buttons on universal side or do you only render them client side?

**Comment by MurhafSousli** [comment]
> Did you make use of the share buttons on universal side

@u12206050 I just used it the same way I would use it in a normal angular app and it worked, I'm not sure what you mean by make use of them on universal side because I'm not technically familiar with universal yet. I have been told that global variables like `window` is not available in node apps, and we can't get rid of `window` completely since there is no other way to open the sharing dialog in a new window (not new tab).
