### ISSUE TITLE
Consider using tags for releases

### ISSUE THREAD

**Issue by jcao02** [MurhafSousli/ng2-sharebuttons#65]
And keep the last version published in npm.

**Comment by MurhafSousli** [comment]
It's not ready yet, **linkedin** and **pinterest** count are not working because of `JSONP` bug [#14267](https://github.com/angular/angular/issues/14267). we are waiting until its fixed.

**Comment by MurhafSousli** [comment]
@jcao02 I've publish a beta version to npm

**Comment by jcao02** [comment]
Cool @MurhafSousli. I'll use it right away
