### ISSUE TITLE
Image doesn't get displayed ! Please help

### ISSUE THREAD

**Issue by akashs25** [MurhafSousli/ng2-sharebuttons#68]
When i pass [image]="  'http://www.xyz.com/image.jpg?alt=media&token=xyz12345'   "
It doesn't share  the image. When i checked the url of image that is being share, 

It was src="    'http://www.xyz.com/image.jpg?alt=media'   " i.e. **The token went missing**.
Due to the above problem i am unable to use the module. Kindly revert back asap.

**Comment by MurhafSousli** [comment]
@akashs25 have you tried to `let testSrc = encodeURIComponent(imageSrc);` `[image]="testSrc"` ?

**Comment by MurhafSousli** [comment]
@akashs25  Please update to version 2, if you still have the issue, feel free to reopen

**Comment by akashs25** [comment]
@MurhafSousli    Thanks a lot for your reply. 

**let testSrc = encodeURIComponent(imageSrc); [image]="testSrc"** did work!
