### ISSUE TITLE
Sanitize warning

### ISSUE THREAD

**Issue by danillobarbosa** [MurhafSousli/ng2-sharebuttons#70]
WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).

How to fix this?

**Comment by tinesoft** [comment]
Hi @danillobarbosa ,

The sanitization via usage of `[innerHTML]` is done on purpose to prevent XSS attacks, by removing potentially harmful code from button's custom template.  But maybe we should trust given HTML, as this library is intended for developers usage ...

What content are you passing, and what is the (stripped) output?

**Comment by danillobarbosa** [comment]
I'm using it as in the documentation.
Is there a way to suppress these alerts without console?

**Comment by tinesoft** [comment]
> I'm using it as in the documentation.

I'm sorry, i don't really follow you.. **_what_** are you using like in the documentation?
and again, **_what content_** is being stripped out and _**where**_ are you using it? (which `@Input`?)

**Comment by danillobarbosa** [comment]
`````html
<div class="social-share">
          <share-button [button]="socialButtons.twitter" [url]="socialButtons.noticiaUrl(post.slug)" class="mr-1"></share-button>
          <share-button [button]="socialButtons.facebook" [url]="socialButtons.noticiaUrl(post.slug)"></share-button>
</div>
``````
``````javascript
noticiaUrl(slug: string) {
    return Config.BASE_URL + 'noticias/' + slug;
  }

  twitter = new ShareButton(
    ShareProvider.TWITTER,              //choose the button from ShareProvider
    "<i class='fa fa-twitter' aria-hidden='true'></i>",    //set button template
    'twitter'                           //set button classes
  );
  facebook = new ShareButton(
    ShareProvider.FACEBOOK,              //choose the button from ShareProvider
    "<i class='fa fa-facebook' aria-hidden='true'></i>",    //set button template
    'facebook'                           //set button classes
  );
````````

**Comment by tinesoft** [comment]
We only use sanitization(via usage of `[innerHTML]` ) for the  **button's template** (see below)

**share-button.component.html**
```
<button (click)='share()' [innerHTML]="button.template" [ngClass]="button.classes"></button>
<span *ngIf="count && shareCount" class="sb-button-count">{{ shareCount | nFormatter: 1 }}</span>
```

and the custom template you are using, contains no harmful code...
So what is stripped out?

**Comment by MurhafSousli** [comment]
@danillobarbosa I guess this issue is solved in version 2
