### ISSUE TITLE
Error: No provider for ShareButtonsService!

### ISSUE THREAD

**Issue by RathodGirish** [MurhafSousli/ng2-sharebuttons#73]
I am getting error of No provider for ShareButtonsService. Please any suggestion?

**Comment by tinesoft** [comment]
Hi @RathodGirish 

Which version of the library are you using?
If on **>=2.0.0**, make sure you call `ShareButtonsModule`**.forRoot()** when importing the module.

```
import {ShareButtonsModule} from "ng2-sharebuttons";
@NgModule({
  imports: [
    ShareButtonsModule.forRoot()
  ]
})
```

**Comment by RathodGirish** [comment]
Yes that's resolved @tinesoft 

Now getting another problem.

Uncaught Error: Can't resolve all parameters for ShareButton: (?, ?, ?).

My template is like this :

       <share-button 
           [button]='fbButton' 
           [description]="description" 
           [tags]="tags">
       </share-button> 

And in component I am using:

          fbButton;
          tags = 'My fb share';
          description = "This is a first sharing description";

         ngOnInit() {
		this.fbButton = new ShareButton(ShareProvider.FACEBOOK, 
                    "<img src='../assets/piblic/img/fb-share.svg'>",	
	            'facebook'
      	        );
         }

**Comment by tinesoft** [comment]
Hi, 

This might be a bug introduced in V2, as the single `<share-button>` component is no longer exported in the `ShareButtonsModule` (even if the related files are present in the NPM package)....

Until then, you can either :
- use the new `[shareButton] `directive to customize an existing button element
- use the `<share-button`**s**`>` component (note the **"s"** at the end) 

**my-component.html**
```
<share-buttons 
       [facebook]="fbButton"
       [description]="description" 
       [tags]="tags"
></share-buttons>
```
_**note**: if you don't want a button to appear, you can hide it with this: `[twitter]="false"` for e.g_

and in the component 

**my-component.ts**
```
   fbButton = '<img src="../assets/piblic/img/fb-share.svg">';
   tags = 'My fb share';
   description = 'This is a first sharing description';
```

**Comment by RathodGirish** [comment]
Thanks a lot @tinesoft 
That's working fine.

Now there are 2 problems while display button and sharing content.

![capturefb issue](https://cloud.githubusercontent.com/assets/20778089/23209501/78d8187c-f91f-11e6-8894-2870833d5ee0.PNG)

![capturefb issue2](https://cloud.githubusercontent.com/assets/20778089/23209529/8e37aa2a-f91f-11e6-8d73-a481aada49ee.PNG)

Thanks in advance :)

**Comment by tinesoft** [comment]
Which solution did you end up with? the` [shareButton]` directive or the `<share-buttons>` component ?
For the later, please note that it is: 

`fbButton = '<img src="../assets/piblic/img/fb-share.svg">';`

and not:
```
fbButton = new ShareButton(ShareProvider.FACEBOOK, 
            "<img src='../assets/piblic/img/fb-share.svg'>",	
            'facebook');
```

For most buttons, the sharing window does not work on http://localhost (only on deployed URL)
You can set the [url] to a existing URL to test and make sure everything works as expected

**Comment by RathodGirish** [comment]
OK @tinesoft  I have added [url]
Thanks a lot :)
Resolved using : 👍 

                         <share-buttons 
                            [title]="'Testing title'"
                            [url]="'https://facebook.com'"
                             [twitter]=false
                             [google]=false
                             [pinterest]=false
                             [linkedIn]=false
                             [tumblr]=false
                             [reddit]=false
                             [stumbleUpOn]=false
                             [whatsApp]=false
                             [description]="description" 
                             [tags]="tags"
                            ></share-buttons>

But I am not able to set : [shareTitle]="'Share Facebook Title'"
**Getting Error : Can't bind to 'shareTitle' since it isn't a known property of 'share-buttons'.**

I want to set dynamic title, desciption and imageUrl.
Please suggest.

Thanks

**Comment by tinesoft** [comment]
`[shareTitle]` and `[totalCount]` have been removed in v2, as most users didn't use it anyway.

You want to use  **[title]**, **[image]** and **[description]** on `<share-buttons>` to customize what is shared (note that some providers don't support image url ).

Current `README.md` still need to be updated to reflect most of changes from v2.
Until then, you can have a look to source code directly and/or demo app, to see new usages.

**Comment by MurhafSousli** [comment]
@RathodGirish I have updated both changelog and readme, I will close this for now
