### ISSUE TITLE
Dynamic title, description and image not working.

### ISSUE THREAD

**Issue by RathodGirish** [MurhafSousli/ng2-sharebuttons#75]
I am setting dynamic value of title, description and image. But not working.
Template : 

         <share-buttons 
               [title]="fbShareTitle"
               [url]="'http://maprentalsstaging.azurewebsites.net'"
               [twitter]=false
               [google]=false
               [pinterest]=false
               [linkedIn]=false
               [tumblr]=false
               [reddit]=false
               [stumbleUpOn]=false
               [whatsApp]=false
               [description]="fbShareDescription" 
               [tags]="'tags'">
        </share-buttons>

In component I am setting like this : 

       fbShareTitle = '';
       fbShareDescription = "";

       ngOnInit() {
		this.fbShareDescription = 'This is a first sharing description';   // Working fine here.
		this.fbShareTitle = 'Testing';             // Working fine here

                this.propertyService.getProperyById(this.propertyId)
		     .subscribe((data: any) => {
		            	let object = Object.assign({}, data);
		            	this.fbShareDescription = object.desc;    // This is not working
		                this.fbShareTitle = object.title;     // This is not working
                });
       }

Getting error : 

![capture error](https://cloud.githubusercontent.com/assets/20778089/23253539/f15d8dca-f9da-11e6-875f-1c305612bdf0.PNG)

Please any suggestion? 
Thanks

**Comment by MurhafSousli** [comment]
@RathodGirish facebook will always give you this on localhost, try some live URL and see..

**Comment by RathodGirish** [comment]
Yeah thank @MurhafSousli 

Its working fine in live URL.

Thanks a lot :)
