### ISSUE TITLE
Facebook share show blank dialog for a second and disappear

### ISSUE THREAD

**Issue by marcocasadio** [MurhafSousli/ng2-sharebuttons#77]
On production server I have this issue:
When I click on button to share the page on Facebook I get a blank dialog for a second and later it disappear.

![senza titolo 2](https://cloud.githubusercontent.com/assets/7057518/23287099/9b04bece-fa3b-11e6-8f7c-6caab13a99d8.png)

Can you help me?

**Comment by MurhafSousli** [comment]
show me your code

**Comment by marcocasadio** [comment]
Hi,
this is my code:
`   <share-buttons
      [pinterest]="false"
      [linkedIn]="false"
      [tumblr]="false"
      [reddit]="false"
      [stumbleUpOn]="false"
      [title]="pageTitle"
      [description]="pageDescription"
      [image]="pageImage"
      [tags]="['NeverAloneApp','LiveTrack']">
   </share-buttons>`

Thank you

**Comment by JvJefke** [comment]
I had the same problem but fixed it by doing this:

I changed this:
```
<share-buttons
            *ngIf="blog"
            [url]="url"
            [title]="'title - ' + blog.title"
            [description]="blog.summary"
            [tumblr]="false"
            [pinterest]="false"
            [stumbleUpOn]="false"
            [reddit]="false"
            [whatsApp]="false"
            [defaultStyle]="false">
</share-buttons>
```
to this:
```
<share-buttons
            *ngIf="blog"
            [url]="url || '' "
            [title]="'title - ' + blog.title"
            [description]="blog.summary || '' "
            [tumblr]="false"
            [pinterest]="false"
            [stumbleUpOn]="false"
            [reddit]="false"
            [whatsApp]="false"
            [defaultStyle]="false">
</share-buttons>
```

I hope this also helps you.

I'm guessing it breaks somewhere because of a `undefined` or `null` value.

**Comment by MurhafSousli** [comment]
You are probably trying to share the page from `localhost`, Facebook will always give you blank on localhost like in #75

**Comment by marcocasadio** [comment]
@JvJefke thank you! I'll try it!
@MurhafSousli nope, I'm on the production server. If you want to try: https://neveralone.site/livetrack/#/users/marcocasadio (PIN: 31279)

**Comment by MurhafSousli** [comment]
@marcocasadio I can't find the buttons to try!

**Comment by MurhafSousli** [comment]
@marcocasadio this has to do with the `#` in your URL structure

**Comment by MurhafSousli** [comment]
@marcocasadio 

> Facebook indexes URLs and the # is not considered part of the URL.
A solution is to use "hashbang" #! notation instead.

source:  [SO](http://stackoverflow.com/a/29674943/1015648)

**Comment by marcocasadio** [comment]
Hi,
I'm in production without hash (#) on URL to share but Facebook share still not working.
You can check it here:
https://neveralone.live/users/marcocasadio

Any idea?
Thanks

**Comment by marcocasadio** [comment]
I have discovered that the issue is related to [image]="pageImage". Maybe the URL of image into "pageImage" isn't correct and Sharer for Facebook break up. Anyway if you want to change this with a fallback, checking the URL, would be nice

**Comment by MurhafSousli** [comment]
@marcocasadio in my humble opinion, a developer should be responsible for giving a valid URL, this module already fallback to meta tags if the developer didn't provide them. so you can simply make your own fallback function that results in a valid URL  `[image]="getPageImage(pageImage)"` 
```ts
getPageImage(img){
    if(img !== 'whatever'){
        return defaultImage;
    }
    return img;
}
```

**Comment by marcocasadio** [comment]
@MurhafSousli I agree with you! It was only to inform you that you could do a fallback checking the URL, to have a more robust plugin.
Thank you!

**Comment by MurhafSousli** [comment]
@marcocasadio thank you, in case you can improve the plugin, we welcome pull requests 🙂
