### ISSUE TITLE
Title text can't be included on Twitter Button

### ISSUE THREAD

**Issue by gorilla-b** [MurhafSousli/ng2-sharebuttons#78]
Hi I could implement share bottons.
But the title text can't be included on the Twitter button when I click button.
The Facebook button is going well.

`    <share-buttons
       [showCount]="ture"
       [title]="title"
       [pinterest]="false"
       [reddit]="false"
       [stumbleUpOn]="false"
       [google]="false"
       [whatsApp]="false"
       [tumblr]="false"
       [linkedIn]="false"
       ></share-buttons>`

Thank you.

**Comment by MurhafSousli** [comment]
Hi @gorilla-b, currently you can use the `[description]` input for tweet text

**Comment by gorilla-b** [comment]
It works well!
I am grateful for your support.

**Comment by MurhafSousli** [comment]
@gorilla-b you can support the module by giving a star ⭐
