### ISSUE TITLE
Getting only the like counts

### ISSUE THREAD

**Issue by karljv** [MurhafSousli/ng2-sharebuttons#80]
Is there any easy way to just pass a social media profile type from ShareProvider, ala. FACEBOOK and a FACEBOOK url and get the like count, without creating a button? 

I have pondered around the source code, but the count() functions seem to be private and I'd rather not tamper with the source code.

I am asking this because on some pages, I just need to show the like count of some social profiles, without having a button on sharing, and furthermore I need to do this dynamically, eg. ngFor="let socialProfile of socialProfiles" and as such, using components as you suggested in your advanced usage scenarios ( eg. on ngOnInit use this.twitterButton = ...) and then using that in the directive requires too much code for a simple task.

**Comment by karljv** [comment]
Also I think, this project is vital and awesome, but as a programmer, I've no real need for premade buttons and such, but more need for functionality I can anchor on my own DOM items. And data I can pull for services, ala give in FACEBOOK and an URL, and get the like count (as described above).

**Comment by MurhafSousli** [comment]
@karljv Yes you can, 
```
<div style="display: none" [shareButton]="'facebook'" (count)="fbCount = $event"></div>
<div class="fb-count">{{fbCount | nFormatter}}</div>
```

**Comment by karljv** [comment]
I put a variable
public fbCount 
into my components.ts

and inside component.html I have
<div style="display: none;"
                                                                     [shareButton]="'facebook'"
                                                                     [sbUrl]="'https://www.facebook.com/facebook/'"
                                                                     (sbCount)="fbCount = $event"></div>
                                                                <h6 class="upload-social-followings">
                                                                    {{fbCount}}
                                                                </h6>

Yet the h6 is empty. fbCount is undefined. What am I doing wrong here?

**Comment by MurhafSousli** [comment]
@karljv I'm showing you the usage code, and you are applying completely different code. but first:
 1 - Don't shortcut pipe name!! use `{{fbCount | nFormatter}}` not `{{ fbCount | nformat }}`
 2 - Please align your code, angular users should have the skills to align code in issues!

```html
<div style="display: none" [shareButton]="'facebook'" [sbUrl]="someUrl" (sbCount)="fbCount = $event"></div>
<div class="fb-count">{{fbCount | nFormatter}}</div>
```
in your component
```ts
class someComponent{
   //
    fbCount: number = 0;
    someUrl = 'https://reddit.com'; //or any link you want
   //
}

**Comment by karljv** [comment]
1. I used the correct name in code, it was a typo here.
2. ok

New code

component.ts
```
export class ListingCreateComponent implements OnInit {
    // START - ShareButtons
    public fbCount: number              = 0;
    public facebookUrl                  = "https://www.facebook.com/facebook/"
    // END - ShareButtons
```

component.html
```
<div style="display: none;" [shareButton]="'facebook'" [sbUrl]="facebookUrl" (sbCount)="fbCount = $event"></div>
<h6 class="upload-social-followings">{{fbCount | nFormatter}}</h6>
```

The result is still a zero and I don't see any requests made in the network tab

**Comment by MurhafSousli** [comment]
@karljv Did you see a number for `[sbUrl]="'https://reddit.com'"` ?

**Comment by karljv** [comment]
Hmmm, it is still blank I'm afraid.

Maybe I am doing something else wrong.

The related imports in my component.ts are

`import { ShareButtonsService, ShareButton, ShareProvider }                      from 'ng2-sharebuttons';`

My module load order is

shared.module.ts
```
import { ShareButtonsModule }           from 'ng2-sharebuttons';

imports: [ ShareButtonsModule.forRoot() ...
```

is included in listings.module.ts
```
imports: [ SharedModule, ....
```

is included in app.module.ts
`imports: [ ListingsModule, ....`

**Comment by karljv** [comment]
Since the developer doesnt know his own plugin, I decided to go poking around the source code. He forgot to tell me that for the likes to be counted, you have to include the

`[sbShowCount]="true"`

on the damn directive.

Hope this helps anyone else trying to get this to work!

The modules were fine, I ended up having the forRoot declaration in my app.module.ts and just the ShareButtonsModule imports and exports in my shared.module.ts

**Comment by MurhafSousli** [comment]
@karljv I don't have to feed you with a spoon, this is explained in details in the docs and in the demo, but you don't read [ITS HERE](https://github.com/MurhafSousli/ng2-sharebuttons#sharebutton-share-directive-for-single-button). and no one works for you here... you should be thankful that I'm replying you.

**Comment by tinesoft** [comment]
@karljv 

> Since the developer doesnt know his own plugin, I decided to go poking around the source code. He forgot to tell me that for the likes to be counted, you have to include the
> 
> [sbShowCount]="true"
> 
> on the damn directive

Please, be respectful when using an library someone spent his _free time_ writing and decided to share.
Should i remind you this is an _opensource_ project and that you don't pay anything for using it or for support.

The author did provide you with useful information in his post(the very same day!) , the documentation and demo application are pretty complete and we work hard to keep them update to date.

Please keep that in mind for next time.

Yours sincerely
