### ISSUE TITLE
:root break the layout of my entire app

### ISSUE THREAD

**Issue by Tuizi** [MurhafSousli/ng2-sharebuttons#81]
Hello,

This code:
```
:root {
  font-size: 16px;
}
```

Will break every project using em/rem units. When using thoses, the font-size is most of the time set to `font-size: 62.5%` to be able to have 1em = 10px, but because of this line all the layout is broken. 

Why imposing a font-size to all the application (`:root` = `<html>`), why not only `:host` ?

**Comment by MurhafSousli** [comment]
Will fix this in the next release
