### ISSUE TITLE
Some features doesn't work on all social network buttons

### ISSUE THREAD

**Issue by Hanzofm** [MurhafSousli/ng2-sharebuttons#83]
For example:

[title], [description] and [image] doesn't work on Google plus
[image] doesn't work on twitter, it would be possible to add image feature on twitter?
[image] doesn't work on linkedin

whatsapp share button open a blank screen but doesn't open whatsapp (EDIT: not work if title or description has been  configured. The image not work)

what would be wrong? Thanks

**Comment by MurhafSousli** [comment]
@Hanzofm thanks for the feedback,
It depends on what the service offers, most these services doesn't accept more than the URL as a parameter, so you should set these values using the meta tags to get it work (which is done on the server side).
However some services accepts images parameter in the link, like fb and pinterest.
G+ only accept the URL.
Twitter and LinkedIn don't accept an image parameter.

**Comment by Hanzofm** [comment]
Sorry, could you explain me a little more how to use the meta tags?  I have to set meta tags individually for each service on head (index.html)? How set then dinamically the url to share?

What is "og:.."? Could you provide me another example?

Thanks for your work

**Comment by MurhafSousli** [comment]
Yes, if you are using angular-cli, which is a client app, you can only set them once using the html for more info read [this](http://ogp.me/). meta tags should be set from the server side, because these social services can't read your angular app, they just read the tags which they get from your server. to shorten things for you, you won't be able to set meta tags dynamically unless you are using universal (or a server rendering shell).

**Comment by Hanzofm** [comment]
Thanks, I'll read it.

For the moment, this is my working solution:

```
<img  [shareButton]="'facebook'"
                                  [sbUrl]="'http://www.valenciacf.com'"
                                  [sbImage]="'http://1.bp.blogspot.com/-UTG_QBXdFvc/UGOBID_zYnI/AAAAAAAAAB8/2bviUM96llw/s1600/gatete.jpg'"
                                  [sbTitle]="'Titulo facebook de prueba'"
                                  [sbDescription]="'Descripcion facebook de prueba'"
                                    mdTooltip="Publicar en Facebook"
                                  src="../../../app/Assets/img/facebook-box.png">
                            <img  [shareButton]="'twitter'"
                                  [sbUrl]="'http://www.valenciacf.com'"
                                  [sbDescription]="'Descripcion facebook de prueba'"
                                  [sbTags]="'hola, adios'"
                                    mdTooltip="Publicar en Twitter"
                                  src="../../../app/Assets/img/twitter.png">
                            <img  [shareButton]="'whatsapp'"
                                  [sbUrl]="'http://www.valenciacf.com'"
                                    mdTooltip="Publicar en  WhatsApp"
                                  src="../../../app/Assets/img/whatsapp.png">
                            <img  [shareButton]="'pinterest'"
                                  [sbUrl]="'http://www.valenciacf.com'"
                                  [sbImage]="'http://1.bp.blogspot.com/-UTG_QBXdFvc/UGOBID_zYnI/AAAAAAAAAB8/2bviUM96llw/s1600/gatete.jpg'"
                                  [sbDescription]="'Descripcion pinterest de prueba'"
                                  [sbTitle]="'Titulo Pinterest de prueba'"
                                  mdTooltip="Publicar en  Pinterest"
                                  src="../../../app/Assets/img/pinterest-box.png">
                            <img  [shareButton]="'linkedin'"
                                  [sbUrl]="'http://www.valenciacf.com'"
                                  [sbDescription]="'Descripcion linkedin de prueba'"
                                  [sbTitle]="'Titulo Linkedin de prueba'"
                                  mdTooltip="Publicar en  Linkedin"
                                  src="../../../app/Assets/img/linkedin-box.png">
                            <img  [shareButton]="'googleplus'"
                                  [sbUrl]="'http://www.valenciacf.com'"
                                  mdTooltip="Publicar en Google +"
                                  src="../../../app/Assets/img/google-plus-box.png">
                            <img  [shareButton]="'tumblr'"
                                  [sbUrl]="'http://www.valenciacf.com'"
                                  mdTooltip="Publicar en  Tumblr"
                                  src="../../../app/Assets/img/tumblr.png">
```

It would be good to list the available options of each provider on the description of the library.


What have you thought about the future features of the library?

Thanks for all

**Comment by MurhafSousli** [comment]
@Hanzofm Hi again, I was going by issues and I just noticed your last comment now

I've updated the docs in the wiki, I hope this helps

|              |   URL    |    Title   |  Description  |     Image   |   Tags   |
|   :---:      |  :---:   |    :---:   |     :---:     |     :---:   |   :---:  |
|   facebook   |    ✔    |     ✔      |       ✔      |      ✔      |    ✖    |
|   twitter    |    ✔    |     ✔      |       ✖      |      ✖      |    ✔    |
|   google+    |    ✔    |     ✖      |       ✖      |      ✖      |    ✖    |
|   linkedin   |    ✔    |     ✔      |       ✔      |      ✖      |    ✖    |
|  pinterest   |    ✔    |     ✖      |       ✔      |      ✔      |    ✖    |
|   tumblr     |    ✔    |     ✖      |       ✔      |      ✖      |    ✔    |
|   whatsapp   |    ✔    |     ✔      |       ✔      |      ✖      |    ✖    |
|    reddit    |    ✔    |     ✔      |       ✖      |      ✖      |    ✖    |
| stumbleupon  |    ✔    |     ✖      |       ✖      |      ✖      |    ✖    |

**Comment by Hanzofm** [comment]
Thanks, I've just updated to ngx version. Thanks for new features.
