### ISSUE TITLE
Is there a way to turn off whatsapp in the bar?

### ISSUE THREAD

**Issue by grenager** [MurhafSousli/ng2-sharebuttons#85]
This attribute seems to be missing... Thanks!

**Comment by MurhafSousli** [comment]
@grenager  Did you try `[whatsapp]="false"` ?

**Comment by grenager** [comment]
Yes I have, and I get the following error:

Unhandled Promise rejection: Template parse errors:
> Can't bind to 'whatsapp' since it isn't a known property of
> 'share-buttons'.


This does NOT happen, BTW with [pinterest]="false" or any of the other
providers. Sorry to not be clearer in the initial request. Thank you for
the great library!

**Comment by MurhafSousli** [comment]
sorry, it's `[whatsApp]` input is "case sensitive"

**Comment by grenager** [comment]
Sweet! Thank you.
