### ISSUE TITLE
image and event count not working on twitter

### ISSUE THREAD

**Issue by hackeurtalibe** [MurhafSousli/ng2-sharebuttons#87]
Hi i have this code :
`      <div>
        <button class="btn btn-facebook " (sbCount)="sumCounts($event)" [shareButton]="'facebook'"[sbUrl]="url+magazine.id" [sbShowCount]="true" [sbTitle]="'Magazine'" [sbImage]="magazine.coverpageImage" [sbDescription]="'Découvrer mon dernier magazine sur Folomi'"   (click)="back()"    ><i class="fa fa-facebook"></i></button>
        <button  class="btn btn-twitter " (sbCount)="sumCounts($event)" [shareButton]="'twitter'" [sbUrl]="url+magazine.id" [sbShowCount]="true" [sbTitle]="'Magazine'" [sbImage]="magazine.coverpageImage" [sbDescription]="'Découvrer mon dernier magazine sur Folomi'"   (click)="back()"   ><i class="fa fa-twitter"></i></button>
        <button class="btn btn-google " (sbCount)="sumCounts($event)" [shareButton]="'GOOGLEPLUS'" [sbUrl]="url+magazine.id" [sbShowCount]="true" [sbTitle]="'Magazine'" [sbImage]="magazine.coverpageImage" [sbDescription]="'Découvrer mon dernier magazine sur Folomi'" (click)="back()"   ><i class="fa fa-google"></i></button>
      </div>`
Angular 2 version 2.4.9
the facebook image link is showed when sharing and also the event count work but google and twitter don't show the image, the event count is not working with twitter, description not showed in google+.
Please help

**Comment by MurhafSousli** [comment]
twitter does not provide share counts.
twitter and google+ does not accept image as a parameter, but for g+ use `og:image` tag
