### ISSUE TITLE
I need to append 'id' into my url

### ISSUE THREAD

**Issue by Carol-Dsouza** [MurhafSousli/ng2-sharebuttons#88]
Hi,

In my html I have a list of names & their corresponding id's.
This is how I'm using the share buttons in the html:
  <share-buttons [url]="univDetailLiveUrl"  (click)="shareId(id)"
                                        [count]="false"
                                        [totalCount]="true"
                                        [defaultStyle]= "true"
                                        (popUpClosed) = "true"
                                        [google]="googleInner"
                                        [pinterest]="false"
                                        [linkedIn]="false"
                                        [tumblr]="tumblrInner"
                                        [reddit]="false"
                                        [stumbleUpOn]="false">
                                  </share-buttons>  

I've used a click function 'shareId()' to  pass id into my url.

This is how I'm calling the shareId() function in the component:
     shareId(id) {
       this.univDetailLiveUrl = 'http://abc.azurewebsites.net/+ id;
     }

When I click any share button for the first time, this function is not called & it takes window.location.href as the sharing url.

When I click it the next time, this function is called & the id is passed, but the id is of the previous click.
i.e. say the first time I clicked the name 'ABC', so its id '1' was passed to the function but not called.
    the next time I clicked another name 'XYZ, so it's id '2' was passed & function was called but the share url showed the id as '1' instead of '2'.

What must I do to overcome this issue?

**Comment by MurhafSousli** [comment]
I'm not sure if I understood correctly what you are trying to do, but you can't use `click()` function on  `<sharebuttons>`, What you need to do is to change the URL dynamically `[url]="univDetailLiveUrl"`, so according to how the name is getting selected in the list, use that click event to change `univDetailLiveUrl`

**Comment by Carol-Dsouza** [comment]
Hi,

It was actually very simple.
I just had to write the url as:
[url]=" 'http://abc.azurewebsites.net/' + id 
in the html itself rather than call a separate function.

**Comment by MrPardeep** [comment]
@MurhafSousli 
What If I need to Change URL on the basis of Button (Facebook, Twitter, WhatsApp) click?

**Comment by MurhafSousli** [comment]
Use the `url` input `<share-button [url]="customURL"></share-button>`

**Comment by MrPardeep** [comment]
Let's discuss here https://github.com/MurhafSousli/ngx-sharebuttons/issues/334#issuecomment-425083909
