### ISSUE TITLE
Shared title not working throw me error 

### ISSUE THREAD

**Issue by tonimitrevski** [MurhafSousli/ng2-sharebuttons#89]
![shared_title](https://cloud.githubusercontent.com/assets/15773773/24097973/95105ca4-0d68-11e7-8b17-f8c332816de7.jpg)

**Comment by tonimitrevski** [comment]
Hi all . I want title will be populated with directive
![populated](https://cloud.githubusercontent.com/assets/15773773/24098328/3e91ae08-0d6a-11e7-9546-7b32fb276f41.jpg)

**Comment by MurhafSousli** [comment]
Hi @tonimitrevski, Facebook does NOT allow to change the text on that area.
You can only change the normal title and the description as stated in the docs.

By the way, thanks for notifying me about `[shareTitle]`, it was removed in the new version and should be removed from the docs too
