### ISSUE TITLE
SumCounts method is not working

### ISSUE THREAD

**Issue by vasu592** [MurhafSousli/ng2-sharebuttons#99]
<share-buttons class="withCount" [url]="locationurl" [defaultStyle]="false" [facebook]="fbTemp" [twitter]="twttTemp" [pinterest]="false"
                [linkedIn]="inTemp" [google]="googleTemp" [tumblr]="false" [whatsApp]="false" [reddit]="false" [stumbleUpOn]="false"
                [whatsApp]="false" [stumbleUpOn]="false" [showCount]="false" (count)="sumCounts($event)">
                </share-buttons>

I don't want to show count in front end. I just want to get total count to database. So that i am placing  [showCount]="false" but sumCounts method is not calling in component.

**Comment by MurhafSousli** [comment]
@vasu592 To get the total count, you must activate `[showCount]="true"`. 
but what you can do is simply hide the counts using css 
```
.sb-count{
    display: none;
}
```
Problem solved.
